### ISSUE TITLE
Installation succeeds but links still open in the same tab

### ISSUE THREAD

**Issue by slackline** [davidwilby/openlinksinnewpage#1]
Hi @davidwilby,

I've given this a whirl on a recent set of [slides](https://github.com/ns-rse/reproducibilitea-sheffield-2023-12-06/) and when I render the files locally with `quarto preview` (Quarto version `1.4.504`) and on the GitHub Pages ([deployed here](https://ns-rse.github.io/reproducibilitea-sheffield-2023-12-06/#/high-replicability-of-newly-discovered-social-behavioural-findings-is-achievable.-10.1038s41562-023-01749-9)) where is uses (Quarto version [`](https://github.com/ns-rse/reproducibilitea-sheffield-2023-12-06/actions/runs/7151638884/job/19476157189#step:3:60)) and whilst the extension reportedly [installs](https://github.com/ns-rse/reproducibilitea-sheffield-2023-12-06/actions/runs/7151638884/job/19476157189#step:4:49) ok links don't open in new tabs.

I've used both the advised `quarto add davidwilby/openlinksinnewpage` and in the publish workflow I use `quarto install --no-prompt extension davidwilby/openlinksinnewpage` and the the extension installs.

My initial thought was that it might be down to using the [grantmcdermott/quarto-revealjs-clean: A minimal and elegant presentation theme for Quarto Reveal.js](https://github.com/grantmcdermott/quarto-revealjs-clean) so I disabled it and used the default plain `format: revealjs` but nope, links still open in the same tab. Gave the `serif` theme you've used in your most recent a whirl but no joy, still doesn't open in new tabs.

Checked the source of the rendered pages and there is now `target="_blank"` in any of the HTML markup.

Any suggestions or things you'd like me to try let me know.

**Comment by davidwyld** [comment]
Thanks for testing this out @slackline !

Can I check that you have the following in your document header? 

```yaml
filters:
    - openlinksinnewpage
```

This doesn't get added by the install command, unfortunately.

**Comment by davidwyld** [comment]
Tested this in a PR on your repo: https://github.com/ns-rse/reproducibilitea-sheffield-2023-12-06/pull/1

I wonder if this is supposed to happen automatically somehow? Can't seem to see other examples doing anything different.

**Comment by slackline** [comment]
As usual I rushed around trying things out (too many things pulling me in different directions) but I had only read the _Installation_ and not clocked the _Usage_ section.

Tested locally adding under the `format:` section whilst using the `clean-revealjs` theme...

```yaml
format:
  [clean-]revealjs:
    ...
    filters:
      - openlinksinnewpage
```

...and it works.

Unsurprisingly following the instructions works as expected. I am an idiot and should sit down and focus on tasks!

I wonder though, given that `filters:` works when placed at the top level and also nested under `filters:`if there is a preferred/"correct" way of using it? :thinking:

**Comment by slackline** [comment]
Yep, unsurprisingly following the instructions works as expected. I am an idiot and should sit down and focus on tasks!

I wonder though, given that `filters:` works when placed at the top level and also nested under `filters:`if there is a preferred/"correct" way of using it? :thinking:
